server:
  port: 8001
spring:
  application:
    name: XIGOU-PLAT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: xigou-plat-9001.com #为当前服务器添加实例的标识
    prefer-ip-address: true